"""empty message

Revision ID: 1ee09d9e59d0
Revises: 4f6a788ab689
Create Date: 2024-08-24 03:09:39.598101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee09d9e59d0'
down_revision = '4f6a788ab689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DataAnalyzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('site_information', sa.PickleType(), nullable=True),
    sa.Column('nature', sa.PickleType(), nullable=True),
    sa.Column('climate', sa.PickleType(), nullable=True),
    sa.Column('people', sa.PickleType(), nullable=True),
    sa.Column('benefit', sa.PickleType(), nullable=True),
    sa.Column('intervention_eligibility', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('DataAnalyzer')
    pass
    # ### end Alembic commands ###
