"""empty message

Revision ID: 4f6a788ab689
Revises: c4cd51ca5fb7
Create Date: 2024-08-23 02:29:42.196681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6a788ab689'
down_revision = 'c4cd51ca5fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MapExplorer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('project_duration', sa.Integer(), nullable=False),
    sa.Column('estimated_unplanned_deforestation', sa.Float(), nullable=False),
    sa.Column('rest_target', sa.PickleType(), nullable=False),
    sa.Column('intervention', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('MapExplorer')
    pass
    # ### end Alembic commands ###
