"""empty message

Revision ID: 707148332485
Revises: 7d25892eb598
Create Date: 2026-04-05 11:12:26.297597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '707148332485'
down_revision = '7d25892eb598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DataAnalyzer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_information_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('nature_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('climate_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('people_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('benefit_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('intervention_eligibility_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('DocumentData', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_1_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('section_2_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('section_3_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('section_4_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('section_5_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('MapExplorer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rest_target_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('intervention_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('tbl_logger_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('response_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # with op.batch_alter_table('tbl_user_sessions', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
    #     batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extended_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_column('extended_data_json')

    # with op.batch_alter_table('tbl_user_sessions', schema=None) as batch_op:
    #     batch_op.drop_column('updated_by')
    #     batch_op.drop_column('updated_at')

    with op.batch_alter_table('tbl_logger_logs', schema=None) as batch_op:
        batch_op.drop_column('response_data_json')
        batch_op.drop_column('request_data_json')

    with op.batch_alter_table('MapExplorer', schema=None) as batch_op:
        batch_op.drop_column('intervention_json')
        batch_op.drop_column('rest_target_json')

    with op.batch_alter_table('DocumentData', schema=None) as batch_op:
        batch_op.drop_column('section_5_json')
        batch_op.drop_column('section_4_json')
        batch_op.drop_column('section_3_json')
        batch_op.drop_column('section_2_json')
        batch_op.drop_column('section_1_json')

    with op.batch_alter_table('DataAnalyzer', schema=None) as batch_op:
        batch_op.drop_column('intervention_eligibility_json')
        batch_op.drop_column('benefit_json')
        batch_op.drop_column('people_json')
        batch_op.drop_column('climate_json')
        batch_op.drop_column('nature_json')
        batch_op.drop_column('site_information_json')

    # ### end Alembic commands ###
