"""empty message

Revision ID: 7d25892eb598
Revises: 916cda7ac3cf
Create Date: 2025-06-30 08:49:04.030316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d25892eb598'
down_revision = '916cda7ac3cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polygons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_area_size', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('district', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polygons', schema=None) as batch_op:
        batch_op.drop_column('district')
        batch_op.drop_column('province')
        batch_op.drop_column('country')
        batch_op.drop_column('project_area_size')
    # ### end Alembic commands ###
