"""empty message

Revision ID: 916cda7ac3cf
Revises: 97da85ea242e
Create Date: 2025-05-15 08:00:57.224208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916cda7ac3cf'
down_revision = '97da85ea242e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # with op.batch_alter_table('tbl_user_sessions', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
    #     batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('tbl_user_sessions', schema=None) as batch_op:
    #     batch_op.drop_column('updated_by')
    #     batch_op.drop_column('updated_at')
    pass

    # ### end Alembic commands ###
