"""empty message

Revision ID: 975320c3c290
Revises: aac4013a4025
Create Date: 2024-09-23 12:56:34.570635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975320c3c290'
down_revision = 'aac4013a4025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_logger_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_type_id', sa.Integer(), nullable=True),
    sa.Column('log_type_code', sa.String(length=64), nullable=True),
    sa.Column('log_type_name', sa.String(length=128), nullable=True),
    sa.Column('activity_type_id', sa.Integer(), nullable=True),
    sa.Column('activity_type_code', sa.String(length=64), nullable=True),
    sa.Column('activity_type_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('request_data', sa.PickleType(), nullable=True),
    sa.Column('response_data', sa.PickleType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_logger_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tbl_logger_logs_activity_type_id'), ['activity_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tbl_logger_logs_log_type_id'), ['log_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tbl_logger_logs_session_id'), ['session_id'], unique=False)

    op.create_table('tbl_master_dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('rowstatus', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    
    with op.batch_alter_table('tbl_user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_project', sa.Boolean(), nullable=True))

    # master dictionary init data
    op.execute(
    '''
        INSERT INTO tbl_master_dictionary (code, name, description, type, rowstatus)
        VALUES
            ('LOG_SUCCESS', 'Log Success', null, 'log type', 1),
            ('LOG_FAILED', 'Log Failed', null, 'log type', 1),
            ('user_account_register', 'user_account_register', 'Registered to NbS Tool', 'activity type', 1),
            ('user_account_verification_token', 'user_account_verification_token', 'Account is activated', 'activity type', 1),
            ('user_account_login', 'user_account_login', 'Login to the NbS Tool', 'activity type', 1),
            ('geo_post_polygon', 'geo_post_polygon', 'Specify project area using drawing method and the project area is {{ data.project_area }} HA', 'activity type', 1),
            ('geo_map_upload', 'geo_map_upload', 'Specify project area using upload {{ data.file_type }} file method and project area is {{ data.project_area }} HA', 'activity type', 1),
            ('projects_bind_project', 'projects_bind_project', 'Add project area into project {{ data.project_name }}', 'activity type', 1),
            ('documents_feasibility_template', 'documents_feasibility_template', 'Generate Feasibility Report with section "{{ data.section }}"', 'activity type', 1),
            ('documents_update_document_data', 'documents_update_document_data', '{{ data.operation }} CCB Documentation', 'activity type', 1),
            ('documents_get_document_data', 'documents_get_document_data', 'Preview CCB Documentation', 'activity type', 1),
            ('documents_get_document_docx', 'documents_get_document_docx', 'Download {{ data.type }}', 'activity type', 1),
            ('geo_feature_current_condition', 'geo_feature_current_condition', 'Get Current Condition', 'activity type', 1),
            ('post_incubator_review', 'post_incubator_review', 'Post Document for Incubators to Review', 'activity type', 1),
            ('documents_delete_document_docx', 'documents_delete_document_docx', 'Delete {{ data.type }}', 'activity type', 1);
    '''
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_user_sessions', schema=None) as batch_op:
        batch_op.drop_column('is_project')

    op.drop_table('tbl_master_dictionary')
    with op.batch_alter_table('tbl_logger_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_logger_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_tbl_logger_logs_log_type_id'))
        batch_op.drop_index(batch_op.f('ix_tbl_logger_logs_activity_type_id'))

    op.drop_table('tbl_logger_logs')
    # ### end Alembic commands ###