"""empty message

Revision ID: 97da85ea242e
Revises: 975320c3c290
Create Date: 2024-10-17 11:54:23.196881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97da85ea242e'
down_revision = '975320c3c290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_master_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    # master settings init data
    op.execute(
        '''
        INSERT INTO tbl_master_settings (name, value)
        VALUES
            ('TOKEN_EXPIRE_HOURS', '0'),
            ('TOKEN_EXPIRE_MINUTES', '20'),
            ('MAX_DRAW_AREA', '500000'),
            ('INCUBATOR_EMAIL_LIST', 'fathir.mohamad@wri.org,irsyad.kharisma@wri.org'),
            ('FE_URL', 'https://staging-nbstool.scenecoalition.org/'),
            ('INCUBATOR_DRIVE_ID', '1RquJ5tftnDH7r7UlTgCX7V4GpH2wlqYE');
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_master_settings')
    # ### end Alembic commands ###
