"""empty message

Revision ID: aac4013a4025
Revises: 1ee09d9e59d0
Create Date: 2024-08-25 14:48:37.181235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac4013a4025'
down_revision = '1ee09d9e59d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocumentData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('certification_type', sa.String(length=100), nullable=False),
    sa.Column('section_1', sa.PickleType(), nullable=True),
    sa.Column('section_2', sa.PickleType(), nullable=True),
    sa.Column('section_3', sa.PickleType(), nullable=True),
    sa.Column('section_4', sa.PickleType(), nullable=True),
    sa.Column('section_5', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DocumentList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_status', sa.String(length=100), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('tbl_user_sessions')
    # op.drop_table('DocumentList')
    # op.drop_table('DocumentData')
    pass
    # ### end Alembic commands ###
