"""empty message

Revision ID: c4cd51ca5fb7
Revises: dca3bc4ea3f0
Create Date: 2024-08-22 19:36:53.920821

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c4cd51ca5fb7'
down_revision = 'dca3bc4ea3f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polygons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('polygons', schema=None) as batch_op:
        # perlu cek ini udah di create atau belum indexnya
        # batch_op.create_index('idx_polygons_geom', ['geom'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_polygons_session_id'), ['session_id'], unique=False)

    op.create_table('tbl_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('aoi_total_area', sa.Float(), nullable=True),
    sa.Column('aoi', sa.String(length=100), nullable=True),
    sa.Column('baseline_id', sa.Integer(), nullable=True),
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.Column('intervention_parameter_value', sa.String(length=100), nullable=True),
    sa.Column('benefit_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tbl_sessions_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('tbl_sessions', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_tbl_sessions_session_id'))

    # op.drop_table('tbl_sessions')
    # with op.batch_alter_table('polygons', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_polygons_session_id'))
    #     batch_op.drop_index('idx_polygons_geom', postgresql_using='gist')

    # op.drop_table('polygons')
    pass
    # ### end Alembic commands ###
