"""empty message

Revision ID: dca3bc4ea3f0
Revises: 
Create Date: 2024-08-17 17:35:00.854375

"""
from alembic import op
import sqlalchemy as sa

# init alembic_version
'''
CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);
INSERT INTO alembic_version VALUES ('aac4013a4025');
'''

# revision identifiers, used by Alembic.
revision = 'dca3bc4ea3f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_organization_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organization_type_id', sa.Integer(), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('permission_policy', sa.Integer(), nullable=True),
    sa.Column('extended_data', sa.PickleType(), nullable=True),
    sa.Column('avatar', sa.LargeBinary(), nullable=True),
    sa.Column('size_limit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('tbl_users')
    # op.drop_table('tbl_organization_types')
    pass
    # ### end Alembic commands ###
